# Deploys the release branch to AWS Elastic Beanstalk. Action origin from
# https://github.com/marketplace/actions/beanstalk-deploy
name: Deploy `release` to EB
on:
  push:
    branches:
    - release

env:
  # The name of the Elastic Beanstalk application to deploy to
  EB_APP_NAME: elastic-beanstalk-autodeploy
  # The name of the environment contained within the Elastic Beanstalk app to deploy to  
  EP_ENV_NAME: dev-env
  # What is the AWS IAM role that this action needs to assume once authenticated?
  AWS_ROLE: arn:aws:iam::022217129536:role/ElasticBeanstalkAutodeployRole
  # Which AWS region is our IAM role and Elastic Beanstalk app located in?
  AWS_REGION: us-east-1


permissions:
  id-token: write # Required for requesting JWT
  contents: read  # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        output-credentials: true

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ steps.creds.outputs.aws-access-key-id }}
        aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
        application_name: ${{ env.EB_APP_NAME }}
        environment_name: ${{ env.EB_ENV_NAME }}
        version_label: ${{ github.event.head_commit.message }}
        version_description: ${{ github.SHA }}
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy.zip